### ISSUE TITLE
所有的图标不见了

### ISSUE THREAD

**Issue by fightinggg** [next-theme/plugins#116]
```log
INFO  Validating config
INFO  ==================================
  ███╗   ██╗███████╗██╗  ██╗████████╗
  ████╗  ██║██╔════╝╚██╗██╔╝╚══██╔══╝
  ██╔██╗ ██║█████╗   ╚███╔╝    ██║
  ██║╚██╗██║██╔══╝   ██╔██╗    ██║
  ██║ ╚████║███████╗██╔╝ ██╗   ██║
  ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝   ╚═╝
========================================
NexT version 8.7.0
Documentation: https://theme-next.js.org
========================================
INFO  Start processing
WARN  Since language_switcher is turned on, the caching is disabled to avoid potential hazards.
WARN  The following packages are not found by `@next-theme/plugins`.
WARN  Package subpath './package.json' is not defined by "exports" in /Users/s/src/hexo-blog/node_modules/firebase/package.json
WARN  Cannot find module 'nprogress/package.json'
Require stack:
- /Users/s/src/hexo-blog/node_modules/@next-theme/plugins/index.js
- /Users/s/src/hexo-blog/node_modules/hexo-theme-next/scripts/events/lib/vendors.js
WARN  Maybe you can find the solution here: https://github.com/next-theme/plugins#debug
```
所有的awesome图标不见了
<img width="1593" alt="截屏2021-08-31 下午2 06 34" src="https://user-images.githubusercontent.com/42932982/131450729-ff5e415d-f218-435a-9877-f5e00c486759.png">

在这里你能看到更多的日志 [here](https://github.com/fightinggg/hexo-blog/runs/3469602791?check_suite_focus=true)
正常的博客应该是[这样子](https://fightinggg.github.io/)

修复方法：
当我把版本从 ` "@next-theme/plugins": "https://github.com/next-theme/plugins/tarball/main"` 修改到 ` "@next-theme/plugins": "https://github.com/next-theme/plugins/tarball/1a99dc8a7794306f867ca466802a1af647dda3a4",` 以后，一切恢复了正常

**Comment by stevenjoezhang** [comment]
谢谢反馈，能发一个存在问题的网站的链接吗？我研究一下

**Comment by fightinggg** [comment]
> 谢谢反馈，能发一个存在问题的网站的链接吗？我研究一下

https://hexoblog-0gbcfywu9055bf90-1258727650.tcloudbaseapp.com/
这个镜像站被我隔离了，你可以去看看

**Comment by stevenjoezhang** [comment]
我刚刚发布了 `@next-theme/plugins` 的`8.7.1`版本，你安装一下，应该就没有这个问题了

NexT 每个月初发新版本，有时候会有新旧版本不同步的问题，之后看看能不能用 GitHub Actions 自动把改动同步过去

**Comment by fightinggg** [comment]
> 我刚刚发布了 `@next-theme/plugins` 的`8.7.1`版本，你安装一下，应该就没有这个问题了
> 
> NexT 每个月初发新版本，有时候会有新旧版本不同步的问题，之后看看能不能用 GitHub Actions 自动把改动同步过去

8.7.1不管用，还是gg，一样的报错

**Comment by stevenjoezhang** [comment]
好吧，那和我想的不一样。如果你是用 npm 安装的 NexT，就重新安装`@next-theme/plugins` 8.7.0 版本；如果是用 git 安装的 NexT，就把 NexT 更新到这个 commit https://github.com/next-theme/hexo-theme-next/commit/31d474763562c4308008708eb7da510603bea0d9 之后

**Comment by fightinggg** [comment]
> 好吧，那和我想的不一样。如果你是用 npm 安装的 NexT，就重新安装`@next-theme/plugins` 8.7.0 版本；如果是用 git 安装的 NexT，就把 NexT 更新到这个 commit [next-theme/hexo-theme-next@31d4747](https://github.com/next-theme/hexo-theme-next/commit/31d474763562c4308008708eb7da510603bea0d9) 之后

8.7.1已解决问题

**Comment by xs314** [comment]
实测在 plugins 设置为 local 时 fontawesome 全部消失，设置成外链则正常
![image](https://github.com/next-theme/plugins/assets/55978649/3d1caa1b-7f4e-4bce-9381-c13f39fdb585)
都装了最新版，不懂啥情况
![image](https://github.com/next-theme/plugins/assets/55978649/d7618739-a611-4882-a890-ea94b94a4617)
