### ISSUE TITLE
can't add pictures to the article, I tried almost everything

### ISSUE THREAD

**Issue by tyshezhang** [next-theme/plugins#302]
Dear production team, thank you very much for your development,

I set up my blog in just a few hours, but I now have a big problem: I can't add images to posts, and I've tried almost everything.

At first I tried to write the absolute path to the file to add the image, but the load failed. Later, I downloaded the plug-in hexo-asset-image and put the image in the folder of the same name, but it still failed to load. I also tried to add a network connection, but it still failed. I think I added the way should be right, but why no pictures.

! [](imapge.png)

**Comment by stevenjoezhang** [comment]
Sorry for the late reply. If you are a beginner, I recommend using absolute URLs starting with `http` to insert images. This way, as long as you can ensure that the image link can be opened through a browser, it can also be loaded in your blog post.
